//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodCollectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FoodCollectRequest()
        {
            this.CollectorHistorys = new HashSet<CollectorHistory>();
            this.DistributorHistorys = new HashSet<DistributorHistory>();
            this.FoodCollectRequestHistorys = new HashSet<FoodCollectRequestHistory>();
            this.Processings = new HashSet<Processing>();
        }
    
        public int id { get; set; }
        public string foodType { get; set; }
        public string packagingType { get; set; }
        public int numberofPackages { get; set; }
        public string foodDescription { get; set; }
        public System.DateTime availableDate { get; set; }
        public System.DateTime preferredCollectTime { get; set; }
        public System.DateTime expiryDate { get; set; }
        public string pickUpLocation { get; set; }
        public string statusType { get; set; }
        public int retaurantID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectorHistory> CollectorHistorys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributorHistory> DistributorHistorys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodCollectRequestHistory> FoodCollectRequestHistorys { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Processing> Processings { get; set; }
    }
}
