//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZeroHungerDBEntities : DbContext
    {
        public ZeroHungerDBEntities()
            : base("name=ZeroHungerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<CollectorHistory> CollectorHistorys { get; set; }
        public virtual DbSet<Collector> Collectors { get; set; }
        public virtual DbSet<DistributorHistory> DistributorHistorys { get; set; }
        public virtual DbSet<Distributor> Distributors { get; set; }
        public virtual DbSet<FoodCollectRequestHistory> FoodCollectRequestHistorys { get; set; }
        public virtual DbSet<FoodCollectRequest> FoodCollectRequests { get; set; }
        public virtual DbSet<Processing> Processings { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
