//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task3.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class addchart
    {
        public int chart_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> prod_id { get; set; }
        public string prod_name { get; set; }
        public string prod_price { get; set; }
    
        public virtual user user { get; set; }
    }
}
