//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task3.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public string product_name { get; set; }
        public int product_price { get; set; }
        public int product_quentity { get; set; }
        public int totalPrice { get; set; }
        public int user_id { get; set; }
        public int order_id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
