//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTDExercise.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateTimeDayTable
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string time { get; set; }
        public string dayOfweak { get; set; }
    }
}
